### ISSUE TITLE
Issue to train deterministically 

### ISSUE THREAD

**Issue by ZLI-afk** [cyye001/Con-CDVAE#8]
Hi, thanks for your work. I am recently getting trouble to train with Con-CDVAE deterministically with exactly same data and seed parameters for multiple time, even though I have turned on the `deterministic` option for both training and generation procedures. The generated results that evaluated by the same CGCNN model vary a lot. Do you have any idea what make this happen and how should I fix it? Many thanks.

**Comment by cyye001** [comment]
Thank you for your interest.
I conducted two tests. First, I trained a new model for a few steps with the same random seed twice, and I confirmed that the parameters of the model were identical each time. If I changed the seed, the parameters would differ.
Second, I generated new crystals using the same random seed and the same model. The output was consistent, producing the same crystals each time.
It seems that I didn’t encounter the issue you mentioned. Could you please first confirm whether the inability to reproduce results is caused by the training process or the generation process? Thanks！

**Comment by ZLI-afk** [comment]
Thanks for your reply. I notice that if the same seed adopted for training and the loss will be similar at the first few steps. But as batch number going up (like a hundred), the models will end up different on performance. Is this normal to be expected?

**Comment by cyye001** [comment]
So it seems that this issue is caused by rounding errors. I’m very sorry, but at the moment, I don’t have a good solution to address this problem.

**Comment by ZLI-afk** [comment]
Okey, thanks for your reply. I will close this issue
